### ISSUE TITLE
Reset the elements state back & start drag

### ISSUE THREAD

**Issue by MoNSTRiKcom** [bcakmakoglu/revue-draggable#162] opened 2021-11-15 21:39 UTC
Hi.

Following the manual, the Object returns to its original position, but when you try to move it again, the values ​​get the following:
x: NaN, y: NaN
That is, the subsequent movement is blocked. I tried a lot, but I could not find a solution. Help.

```
 // reset the elements state back to its initial position
    reset(state) {
      state.value = { ...state.value, position:{ x: 0, y: 0 } };
    }
```

_upd._ Found it to work, but not the first time. After pressing the reset button, you need to move the block again and press it again. Then it goes back to the original ...

And I also want to reset it with @stop

**Comment by bcakmakoglu** [comment] 2021-11-15 22:22
Hi!

Can you maybe provide me with a sandbox example of what you're issue exactly is?
You're trying to reset position after the @stop event?

**Comment by MoNSTRiKcom** [comment] 2021-11-15 22:57
Yes!

Pug:
` Draggable(
    :position="containerDragPosition"
    @move="dragStart"
    @stop="dragReset"
  ) 
 template(
      #default="props"
    )
`

Vue:
` methods: {

    dragStart(e) {
      this.currentEvent = e
      const { x, y } = e.data
      this.containerDragPosition.x = x
      this.containerDragPosition.y = y
    },

    rreset() {
      setTimeout(() => {
        this.containerDragPosition.x = 0
        this.containerDragPosition.y = 0
      }, 500);

    },
    dragReset(e) {
      e.value = { ...e.value,  x: 0, y: 0 }
    },
}`

the sandbox cannot be assembled yet.
The idea is that after moving the block, we send a signal to change the backend, but visually everything should remain old with small decorations.

**Comment by bcakmakoglu** [comment] 2021-11-16 13:37
Which Vue version are you using?

I'll try to re-create the problem/solution and will message you back here as soon as I can. :)

**Comment by MoNSTRiKcom** [comment] 2021-11-16 14:38
vue 3
Thanks!

**Comment by bcakmakoglu** [comment] 2021-11-17 11:54
(Didn't mean to close the issue)

Try pulling the v0.3.2 version and giving it another try. I fixed a couple of stuff that seemed to misalign the positions and somewhat make resetting impossible.
Should be fixed (my tests did all work with the code you gave me as an example) now.

Let me know if it works!

**Comment by MoNSTRiKcom** [comment] 2021-11-17 13:29
Thanks. It works!
Moreover, both methods are correct.

**Comment by bcakmakoglu** [comment] 2021-11-17 14:06
@MoNSTRiKcom 
I found another issue actually which causes elements that have been reset to jump from their controlled position to their last known position of draggable.
It should be fixed with v0.3.3 so if you experience trouble with elements jumping around please check that version first :)

**Comment by MoNSTRiKcom** [comment] 2021-11-23 09:55
Version 0.3.7 stopped returning state for @stop="reset"

```pug
Draggable(
    :grid="[sheduler.tableWidthColumn, sheduler.tableHeightRow]"
    :position="containerDragPosition"
    :positionOffset="positionOffset"
    @move="dragMove"
    @start="dragStart"
    @stop="dragReset"
  )
```


```js
dragReset() {
      setTimeout(() => {
        this.containerDragPosition.x = 0
        this.containerDragPosition.y = 0
        this.positionOffset = {x: 0, y: 0}
        this.newDateTime = null
      }, 500)
    },
```

**Comment by bcakmakoglu** [comment] 2021-11-23 10:12
@MoNSTRiKcom 
Should be fixed in the next version too; Seems like I snuck in a regression 😅 sorry.

**Comment by bcakmakoglu** [comment] 2021-11-23 11:30
@MoNSTRiKcom 
Please check out v0.3.8 and let me know if the issue is resolved.

**Comment by MoNSTRiKcom** [comment] 2021-11-23 12:09
Reset working! 💕

**Comment by bcakmakoglu** [comment] 2021-11-23 12:10
Perfect, I'll close the issue again :)

**Closed by bcakmakoglu** 2021-11-23 12:10 UTC
Labels: bug, question
