### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'toggle')

### ISSUE THREAD

**Issue by brenoepics** [bcakmakoglu/revue-draggable#400] opened 2024-02-01 22:24 UTC
**Describe the bug**
revue-draggable.es.js:3 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'toggle')
    at revue-draggable.es.js:3:7735
    at Array.forEach (<anonymous>)
    at b (revue-draggable.es.js:3:7679)
    at revue-draggable.es.js:3:8602
    at runtime-core.esm-bundler.js:2874:88
    at callWithErrorHandling (runtime-core.esm-bundler.js:193:18)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:201:17)
    at hook.__weh.hook.__weh (runtime-core.esm-bundler.js:2854:19)
    at flushPostFlushCbs (runtime-core.esm-bundler.js:369:40)
    at flushJobs (runtime-core.esm-bundler.js:407:5)

**To Reproduce**
1. Install on latest Vue 3 + TS and Vite

**Comment by brenoepics** [comment] 2024-02-01 22:31
It works with 
```html
<template>
    <div v-draggable>
      <HelloWorld msg="Retro Overlay" />
    </div>
</template>
```

but not
```html
<Draggable>
    <div class="box">I use a wrapper</div>
  </Draggable>
```

**Comment by brenoepics** [comment] 2024-02-02 00:34
error TS7016: Could not find a declaration file for module '@braks/revue-draggable'. '/home/runner/work/retro-overlay/retro-overlay/node_modules/@braks/revue-draggable/dist/revue-draggable.es.js' implicitly has an 'any' type.

Probably something related to this, I get dist only but no index.js as other dependencies

**Comment by bcakmakoglu** [comment] 2024-02-14 20:01
Did you import the Draggable component?
The docs are built with Vite + Vue 3 and they use `<Draggable>` mostly and afaik the docs examples all still work 🤔
Do you, by chance, have a sandbox reproduction of this?

**Comment by bcakmakoglu** [comment] 2024-03-09 19:18
@brenoepics ping - any chance for a repro on this?

**Comment by bcakmakoglu** [comment] 2024-03-25 09:03
@brenoepics ping - otherwise I'll have to close the issue for now until I can get a repro for this :/

**Comment by bcakmakoglu** [comment] 2024-03-28 08:39
closed due to insufficient info, please re-open with a repro if necessary.

**Closed by bcakmakoglu** 2024-03-28 08:39 UTC
Labels: bug
